2019-01-28 19:01:00-__init__-DEBUG-Using selector: SelectSelector
2019-01-28 19:01:07-__init__-DEBUG-Using selector: SelectSelector
2019-26-28 19:26:02-log_response-ERROR-Internal Server Error: /apis/user/33427729
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Study\School\e2e\server\backend\views.py", line 91, in user_detail
    password = request.data["password"]
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 100, in user_detail
    return Response(serializer.data)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 562, in data
    ret = super().data
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 514, in to_representation
    for field in fields:
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 375, in _readable_fields
    for field in self.fields.values():
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 363, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 1063, in get_fields
    source, info, model, depth
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 1208, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 1325, in build_unknown_field
    (field_name, model_class.__name__)
django.core.exceptions.ImproperlyConfigured: Field name `friendslast_ip` is not valid for model `user`.
2019-27-28 19:27:00-log_response-ERROR-Internal Server Error: /apis/user/33427729
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Study\School\e2e\server\backend\views.py", line 91, in user_detail
    password = request.data["password"]
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 100, in user_detail
    return Response(serializer.data)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 562, in data
    ret = super().data
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 514, in to_representation
    for field in fields:
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 375, in _readable_fields
    for field in self.fields.values():
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 363, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 1063, in get_fields
    source, info, model, depth
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 1208, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\serializers.py", line 1325, in build_unknown_field
    (field_name, model_class.__name__)
django.core.exceptions.ImproperlyConfigured: Field name `friendslast_ip` is not valid for model `user`.
2019-27-28 19:27:24-__init__-DEBUG-Using selector: SelectSelector
2019-27-28 19:27:38-__init__-DEBUG-Using selector: SelectSelector
2019-28-28 19:28:08-__init__-DEBUG-Using selector: SelectSelector
2019-28-28 19:28:15-__init__-DEBUG-Using selector: SelectSelector
2019-29-28 19:29:19-log_response-ERROR-Internal Server Error: /apis/user/33427729
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 111, in user_detail
    request_id = request.COOKIES["logining_userid"]
KeyError: 'logining_userid'
2019-31-28 19:31:02-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-31-28 19:31:02-__init__-DEBUG-Using selector: SelectSelector
2019-31-28 19:31:18-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-31-28 19:31:18-__init__-DEBUG-Using selector: SelectSelector
2019-35-28 19:35:23-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-35-28 19:35:23-__init__-DEBUG-Using selector: SelectSelector
2019-35-28 19:35:34-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-35-28 19:35:34-__init__-DEBUG-Using selector: SelectSelector
2019-35-28 19:35:40-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-35-28 19:35:40-__init__-DEBUG-Using selector: SelectSelector
2019-35-28 19:35:50-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-35-28 19:35:50-__init__-DEBUG-Using selector: SelectSelector
2019-35-28 19:35:53-log_response-ERROR-Internal Server Error: /apis/user/33427729
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 111, in user_detail
    seriadata = serializer.copy()
AttributeError: 'UserSerializer' object has no attribute 'copy'
2019-36-28 19:36:33-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-36-28 19:36:33-__init__-DEBUG-Using selector: SelectSelector
2019-36-28 19:36:37-log_response-ERROR-Internal Server Error: /apis/user/33427729
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 113, in user_detail
    print(seriadata.data)
AttributeError: 'ReturnDict' object has no attribute 'data'
2019-36-28 19:36:51-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-36-28 19:36:51-__init__-DEBUG-Using selector: SelectSelector
2019-36-28 19:36:53-log_response-ERROR-Internal Server Error: /apis/user/33427729
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 113, in user_detail
    print(seriadata.data)
AttributeError: 'ReturnDict' object has no attribute 'data'
2019-37-28 19:37:02-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-37-28 19:37:02-__init__-DEBUG-Using selector: SelectSelector
2019-37-28 19:37:04-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-37-28 19:37:04-__init__-DEBUG-Using selector: SelectSelector
2019-37-28 19:37:07-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-37-28 19:37:07-__init__-DEBUG-Using selector: SelectSelector
2019-37-28 19:37:55-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-37-28 19:37:55-__init__-DEBUG-Using selector: SelectSelector
2019-37-28 19:37:57-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-37-28 19:37:57-__init__-DEBUG-Using selector: SelectSelector
2019-38-28 19:38:02-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-38-28 19:38:02-__init__-DEBUG-Using selector: SelectSelector
2019-38-28 19:38:04-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-38-28 19:38:04-__init__-DEBUG-Using selector: SelectSelector
2019-38-28 19:38:07-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-38-28 19:38:07-__init__-DEBUG-Using selector: SelectSelector
2019-38-28 19:38:12-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-38-28 19:38:12-__init__-DEBUG-Using selector: SelectSelector
2019-38-28 19:38:42-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-38-28 19:38:42-__init__-DEBUG-Using selector: SelectSelector
2019-38-28 19:38:49-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-38-28 19:38:49-__init__-DEBUG-Using selector: SelectSelector
2019-39-28 19:39:42-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-39-28 19:39:42-__init__-DEBUG-Using selector: SelectSelector
2019-39-28 19:39:48-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-39-28 19:39:48-__init__-DEBUG-Using selector: SelectSelector
2019-39-28 19:39:56-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-39-28 19:39:56-__init__-DEBUG-Using selector: SelectSelector
2019-39-28 19:39:58-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-39-28 19:39:58-__init__-DEBUG-Using selector: SelectSelector
2019-40-28 19:40:02-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-28 19:40:02-__init__-DEBUG-Using selector: SelectSelector
2019-40-28 19:40:07-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-28 19:40:07-__init__-DEBUG-Using selector: SelectSelector
2019-40-28 19:40:09-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-28 19:40:09-__init__-DEBUG-Using selector: SelectSelector
2019-40-28 19:40:16-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-28 19:40:16-__init__-DEBUG-Using selector: SelectSelector
2019-40-28 19:40:19-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-28 19:40:19-__init__-DEBUG-Using selector: SelectSelector
2019-40-28 19:40:25-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-28 19:40:25-__init__-DEBUG-Using selector: SelectSelector
2019-40-28 19:40:27-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-28 19:40:27-__init__-DEBUG-Using selector: SelectSelector
2019-40-28 19:40:32-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-28 19:40:32-__init__-DEBUG-Using selector: SelectSelector
2019-40-28 19:40:35-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-28 19:40:35-__init__-DEBUG-Using selector: SelectSelector
2019-40-28 19:40:40-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-28 19:40:40-__init__-DEBUG-Using selector: SelectSelector
2019-40-28 19:40:46-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-28 19:40:46-__init__-DEBUG-Using selector: SelectSelector
2019-40-28 19:40:48-__init__-DEBUG-Using selector: SelectSelector
2019-47-28 19:47:03-__init__-DEBUG-Using selector: SelectSelector
2019-47-28 19:47:11-__init__-DEBUG-Using selector: SelectSelector
2019-10-30 21:10:35-__init__-DEBUG-Using selector: SelectSelector
2019-10-30 21:10:43-__init__-DEBUG-Using selector: SelectSelector
2019-18-30 21:18:06-__init__-DEBUG-Using selector: SelectSelector
2019-18-30 21:18:30-__init__-DEBUG-Using selector: SelectSelector
2019-18-30 21:18:33-__init__-DEBUG-Using selector: SelectSelector
2019-06-31 11:06:49-log_response-WARNING-Forbidden (CSRF cookie not set.): /apis/user/
2019-08-31 11:08:17-trigger_reload-INFO-D:\Study\School\e2e\server\backend\urls.py changed, reloading.
2019-08-31 11:08:17-__init__-DEBUG-Using selector: SelectSelector
2019-17-31 11:17:19-log_response-WARNING-Forbidden (CSRF cookie not set.): /apis/user/
2019-18-31 11:18:01-log_response-WARNING-Forbidden (CSRF cookie not set.): /apis/user/
2019-18-31 11:18:36-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-18-31 11:18:36-__init__-DEBUG-Using selector: SelectSelector
2019-18-31 11:18:40-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-18-31 11:18:40-__init__-DEBUG-Using selector: SelectSelector
2019-32-31 11:32:43-log_response-WARNING-Not Found: /apis/
2019-39-31 11:39:10-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-39-31 11:39:10-__init__-DEBUG-Using selector: SelectSelector
2019-39-31 11:39:25-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-39-31 11:39:25-__init__-DEBUG-Using selector: SelectSelector
2019-48-31 11:48:08-trigger_reload-INFO-D:\Study\School\e2e\server\server\settings.py changed, reloading.
2019-48-31 11:48:08-__init__-DEBUG-Using selector: SelectSelector
2019-48-31 11:48:12-trigger_reload-INFO-D:\Study\School\e2e\server\server\settings.py changed, reloading.
2019-48-31 11:48:12-__init__-DEBUG-Using selector: SelectSelector
2019-48-31 11:48:20-trigger_reload-INFO-D:\Study\School\e2e\server\server\settings.py changed, reloading.
2019-48-31 11:48:20-__init__-DEBUG-Using selector: SelectSelector
2019-51-31 11:51:47-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-51-31 11:51:47-__init__-DEBUG-Using selector: SelectSelector
2019-54-31 11:54:30-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-54-31 11:54:30-__init__-DEBUG-Using selector: SelectSelector
2019-54-31 11:54:32-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-54-31 11:54:32-__init__-DEBUG-Using selector: SelectSelector
2019-01-31 12:01:03-log_response-WARNING-Forbidden (CSRF cookie not set.): /apis/user/
2019-08-31 12:08:14-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-08-31 12:08:14-__init__-DEBUG-Using selector: SelectSelector
2019-08-31 12:08:19-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-08-31 12:08:19-__init__-DEBUG-Using selector: SelectSelector
2019-08-31 12:08:21-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-08-31 12:08:21-__init__-DEBUG-Using selector: SelectSelector
2019-08-31 12:08:39-log_response-WARNING-Forbidden (CSRF cookie not set.): /apis/user/
2019-08-31 12:08:49-log_response-WARNING-Forbidden (CSRF cookie not set.): /apis/user/
2019-09-31 12:09:25-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-09-31 12:09:25-__init__-DEBUG-Using selector: SelectSelector
2019-09-31 12:09:28-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-09-31 12:09:28-__init__-DEBUG-Using selector: SelectSelector
2019-09-31 12:09:58-log_response-WARNING-Not Found: /favicon.ico
2019-15-31 12:15:04-__init__-DEBUG-Using selector: SelectSelector
2019-15-31 12:15:47-trigger_reload-INFO-D:\Study\School\e2e\server\server\settings.py changed, reloading.
2019-15-31 12:15:47-__init__-DEBUG-Using selector: SelectSelector
2019-15-31 12:15:49-trigger_reload-INFO-D:\Study\School\e2e\server\server\settings.py changed, reloading.
2019-15-31 12:15:49-__init__-DEBUG-Using selector: SelectSelector
2019-21-31 12:21:03-trigger_reload-INFO-D:\Study\School\e2e\server\server\settings.py changed, reloading.
2019-21-31 12:21:03-__init__-DEBUG-Using selector: SelectSelector
2019-21-31 12:21:13-trigger_reload-INFO-D:\Study\School\e2e\server\server\settings.py changed, reloading.
2019-21-31 12:21:13-__init__-DEBUG-Using selector: SelectSelector
2019-21-31 12:21:17-trigger_reload-INFO-D:\Study\School\e2e\server\server\settings.py changed, reloading.
2019-21-31 12:21:17-__init__-DEBUG-Using selector: SelectSelector
2019-23-31 12:23:50-log_response-WARNING-Forbidden (CSRF cookie not set.): /apis/user/
2019-40-31 12:40:12-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-31 12:40:12-__init__-DEBUG-Using selector: SelectSelector
2019-40-31 12:40:15-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-31 12:40:15-__init__-DEBUG-Using selector: SelectSelector
2019-40-31 12:40:17-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-31 12:40:17-__init__-DEBUG-Using selector: SelectSelector
2019-40-31 12:40:20-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-40-31 12:40:20-__init__-DEBUG-Using selector: SelectSelector
2019-41-31 12:41:04-log_response-WARNING-Forbidden (CSRF cookie not set.): /apis/user/
2019-41-31 12:41:33-log_response-WARNING-Forbidden (CSRF cookie not set.): /apis/user/
2019-42-31 12:42:11-log_response-WARNING-Forbidden (CSRF cookie not set.): /apis/user/
2019-45-31 12:45:19-trigger_reload-INFO-D:\Study\School\e2e\server\server\settings.py changed, reloading.
2019-45-31 12:45:19-__init__-DEBUG-Using selector: SelectSelector
2019-52-31 12:52:20-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-52-31 12:52:20-__init__-DEBUG-Using selector: SelectSelector
2019-52-31 12:52:23-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-52-31 12:52:23-__init__-DEBUG-Using selector: SelectSelector
2019-52-31 12:52:38-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-52-31 12:52:38-__init__-DEBUG-Using selector: SelectSelector
2019-54-31 12:54:19-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-54-31 12:54:19-__init__-DEBUG-Using selector: SelectSelector
2019-54-31 12:54:22-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-54-31 12:54:22-__init__-DEBUG-Using selector: SelectSelector
2019-19-31 13:19:58-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-19-31 13:19:58-__init__-DEBUG-Using selector: SelectSelector
2019-43-31 13:43:41-log_response-ERROR-Internal Server Error: /apis/user/222222222
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 83, in user_detail
    password = request.data["password"]
AttributeError: 'WSGIRequest' object has no attribute 'data'
2019-45-31 13:45:02-log_response-ERROR-Internal Server Error: /apis/user/222222222
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 83, in user_detail
    password = request.data["password"]
AttributeError: 'WSGIRequest' object has no attribute 'data'
2019-45-31 13:45:28-log_response-ERROR-Internal Server Error: /apis/user/222222222
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 83, in user_detail
    password = request.data["password"]
AttributeError: 'WSGIRequest' object has no attribute 'data'
2019-45-31 13:45:47-log_response-ERROR-Internal Server Error: /apis/user/222222222
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 83, in user_detail
    password = request.data["password"]
AttributeError: 'WSGIRequest' object has no attribute 'data'
2019-47-31 13:47:30-log_response-ERROR-Internal Server Error: /apis/user/111111111
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 83, in user_detail
    password = request.data["password"]
AttributeError: 'WSGIRequest' object has no attribute 'data'
2019-51-31 13:51:22-log_response-ERROR-Internal Server Error: /apis/user/111111111
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 83, in user_detail
    password = request.data["password"]
AttributeError: 'WSGIRequest' object has no attribute 'data'
2019-54-31 13:54:57-log_response-ERROR-Internal Server Error: /apis/user/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 48, in user_list
    post_data = request.data.copy()
AttributeError: 'WSGIRequest' object has no attribute 'data'
2019-55-31 13:55:30-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-55-31 13:55:30-__init__-DEBUG-Using selector: SelectSelector
2019-55-31 13:55:36-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-55-31 13:55:36-__init__-DEBUG-Using selector: SelectSelector
2019-55-31 13:55:56-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-55-31 13:55:56-__init__-DEBUG-Using selector: SelectSelector
2019-56-31 13:56:11-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-56-31 13:56:11-__init__-DEBUG-Using selector: SelectSelector
2019-56-31 13:56:19-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-56-31 13:56:19-__init__-DEBUG-Using selector: SelectSelector
2019-56-31 13:56:43-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-56-31 13:56:43-__init__-DEBUG-Using selector: SelectSelector
2019-57-31 13:57:27-log_response-ERROR-Internal Server Error: /apis/user/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 49, in user_list
    if (len(post_data["password"]) == 64):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'password'
2019-58-31 13:58:22-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-58-31 13:58:22-__init__-DEBUG-Using selector: SelectSelector
2019-58-31 13:58:23-log_response-ERROR-Internal Server Error: /apis/user/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 50, in user_list
    if (len(post_data["password"]) == 64):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'password'
2019-59-31 13:59:45-log_response-ERROR-Internal Server Error: /apis/user/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 50, in user_list
    if (len(post_data["password"]) == 64):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'password'
2019-01-31 14:01:55-log_response-ERROR-Internal Server Error: /apis/user/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 51, in user_list
    post_data["userid"] = random.randint(10000000, 100000000)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\http\request.py", line 467, in __setitem__
    self._assert_mutable()
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\http\request.py", line 464, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
2019-02-31 14:02:48-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-02-31 14:02:48-__init__-DEBUG-Using selector: SelectSelector
2019-12-31 14:12:33-log_response-ERROR-Internal Server Error: /apis/user/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 50, in user_list
    if (len(post_data["password"]) == 64):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'password'
2019-13-31 14:13:26-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-13-31 14:13:26-__init__-DEBUG-Using selector: SelectSelector
2019-13-31 14:13:30-log_response-ERROR-Internal Server Error: /apis/user/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 50, in user_list
    if (len(post_data["password"]) == 64):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'password'
2019-13-31 14:13:47-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-13-31 14:13:47-__init__-DEBUG-Using selector: SelectSelector
2019-13-31 14:13:49-log_response-ERROR-Internal Server Error: /apis/user/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 50, in user_list
    if (len(post_data["password"]) == 64):
TypeError: byte indices must be integers or slices, not str
2019-14-31 14:14:32-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-14-31 14:14:32-__init__-DEBUG-Using selector: SelectSelector
2019-14-31 14:14:40-log_response-ERROR-Internal Server Error: /apis/user/
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 50, in user_list
    if (len(post_data["password"]) == 64):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'password'
2019-16-31 14:16:04-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-16-31 14:16:04-__init__-DEBUG-Using selector: SelectSelector
2019-16-31 14:16:10-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-16-31 14:16:10-__init__-DEBUG-Using selector: SelectSelector
2019-16-31 14:16:12-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-16-31 14:16:12-__init__-DEBUG-Using selector: SelectSelector
2019-31-31 14:31:18-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-31-31 14:31:18-__init__-DEBUG-Using selector: SelectSelector
2019-09-31 15:09:49-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-09-31 15:09:49-__init__-DEBUG-Using selector: SelectSelector
2019-09-31 15:09:55-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-09-31 15:09:55-__init__-DEBUG-Using selector: SelectSelector
2019-45-31 15:45:35-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-45-31 15:45:35-__init__-DEBUG-Using selector: SelectSelector
2019-45-31 15:45:38-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-45-31 15:45:38-__init__-DEBUG-Using selector: SelectSelector
2019-45-31 15:45:56-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-45-31 15:45:56-__init__-DEBUG-Using selector: SelectSelector
2019-45-31 15:45:58-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-45-31 15:45:58-__init__-DEBUG-Using selector: SelectSelector
2019-46-31 15:46:08-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-46-31 15:46:08-__init__-DEBUG-Using selector: SelectSelector
2019-46-31 15:46:17-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-46-31 15:46:17-__init__-DEBUG-Using selector: SelectSelector
2019-46-31 15:46:22-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-46-31 15:46:22-__init__-DEBUG-Using selector: SelectSelector
2019-46-31 15:46:45-log_response-ERROR-Internal Server Error: /apis/user/1234234
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\server\backend\views.py", line 85, in user_detail
    if user_temp.check_password(password):
AttributeError: 'list' object has no attribute 'check_password'
2019-47-31 15:47:00-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-47-31 15:47:00-__init__-DEBUG-Using selector: SelectSelector
2019-47-31 15:47:05-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-47-31 15:47:05-__init__-DEBUG-Using selector: SelectSelector
2019-47-31 15:47:07-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-47-31 15:47:07-__init__-DEBUG-Using selector: SelectSelector
2019-47-31 15:47:15-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-47-31 15:47:15-__init__-DEBUG-Using selector: SelectSelector
2019-47-31 15:47:23-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-47-31 15:47:23-__init__-DEBUG-Using selector: SelectSelector
2019-47-31 15:47:27-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-47-31 15:47:27-__init__-DEBUG-Using selector: SelectSelector
2019-48-31 15:48:27-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-48-31 15:48:27-__init__-DEBUG-Using selector: SelectSelector
2019-48-31 15:48:34-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-48-31 15:48:34-__init__-DEBUG-Using selector: SelectSelector
2019-48-31 15:48:43-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-48-31 15:48:43-__init__-DEBUG-Using selector: SelectSelector
2019-50-31 15:50:25-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-50-31 15:50:25-__init__-DEBUG-Using selector: SelectSelector
2019-50-31 15:50:38-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-50-31 15:50:38-__init__-DEBUG-Using selector: SelectSelector
2019-54-31 15:54:48-trigger_reload-INFO-D:\Study\School\e2e\server\backend\models.py changed, reloading.
2019-54-31 15:54:48-__init__-DEBUG-Using selector: SelectSelector
2019-54-31 15:54:50-trigger_reload-INFO-D:\Study\School\e2e\server\backend\models.py changed, reloading.
2019-54-31 15:54:50-__init__-DEBUG-Using selector: SelectSelector
2019-55-31 15:55:59-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-55-31 15:55:59-__init__-DEBUG-Using selector: SelectSelector
2019-56-31 15:56:10-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-56-31 15:56:10-__init__-DEBUG-Using selector: SelectSelector
2019-56-31 15:56:13-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-56-31 15:56:13-__init__-DEBUG-Using selector: SelectSelector
2019-56-31 15:56:44-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-56-31 15:56:44-__init__-DEBUG-Using selector: SelectSelector
2019-56-31 15:56:49-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-56-31 15:56:49-__init__-DEBUG-Using selector: SelectSelector
2019-56-31 15:56:58-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-56-31 15:56:58-__init__-DEBUG-Using selector: SelectSelector
2019-57-31 15:57:02-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-57-31 15:57:02-__init__-DEBUG-Using selector: SelectSelector
2019-57-31 15:57:14-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-57-31 15:57:14-__init__-DEBUG-Using selector: SelectSelector
2019-57-31 15:57:21-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-57-31 15:57:21-__init__-DEBUG-Using selector: SelectSelector
2019-57-31 15:57:31-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-57-31 15:57:31-__init__-DEBUG-Using selector: SelectSelector
2019-57-31 15:57:34-trigger_reload-INFO-D:\Study\School\e2e\server\backend\views.py changed, reloading.
2019-57-31 15:57:34-__init__-DEBUG-Using selector: SelectSelector
2019-27-31 16:27:47-__init__-DEBUG-Using selector: SelectSelector
