2019-30-27 13:30:28-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-30-27 13:30:28-__init__-DEBUG-Using selector: SelectSelector
2019-13-27 17:13:26-log_response-ERROR-Internal Server Error: /apis/create_new_keyspair
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view backend.views.create_new_keyspair didn't return an HttpResponse object. It returned None instead.
2019-13-27 17:13:26-log_response-WARNING-Not Found: /favicon.ico
2019-13-27 17:13:29-log_response-WARNING-Not Found: /apis/create_new_keyspair¡¢
2019-13-27 17:13:55-log_response-ERROR-Internal Server Error: /apis/create_new_keyspair
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view backend.views.create_new_keyspair didn't return an HttpResponse object. It returned None instead.
2019-14-27 17:14:01-log_response-WARNING-Not Found: /apis/create_new_keyspair/
2019-14-27 17:14:17-log_response-ERROR-Internal Server Error: /apis/create_new_keyspair
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view backend.views.create_new_keyspair didn't return an HttpResponse object. It returned None instead.
2019-14-27 17:14:21-log_response-ERROR-Internal Server Error: /apis/create_new_keyspair
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view backend.views.create_new_keyspair didn't return an HttpResponse object. It returned None instead.
2019-14-27 17:14:30-log_response-WARNING-Forbidden (CSRF token missing or incorrect.): /apis/create_new_keyspair
2019-14-27 17:14:40-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-14-27 17:14:40-__init__-DEBUG-Using selector: SelectSelector
2019-14-27 17:14:44-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-14-27 17:14:44-__init__-DEBUG-Using selector: SelectSelector
2019-16-27 17:16:24-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-16-27 17:16:24-__init__-DEBUG-Using selector: SelectSelector
2019-16-27 17:16:33-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-16-27 17:16:33-__init__-DEBUG-Using selector: SelectSelector
2019-16-27 17:16:41-log_response-ERROR-Internal Server Error: /apis/create_new_keyspair
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 118, in create_new_keyspair
    post_data = json.dumps(request.body)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
2019-17-27 17:17:06-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-17-27 17:17:06-__init__-DEBUG-Using selector: SelectSelector
2019-17-27 17:17:31-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-17-27 17:17:31-__init__-DEBUG-Using selector: SelectSelector
2019-18-27 17:18:01-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-18-27 17:18:01-__init__-DEBUG-Using selector: SelectSelector
2019-18-27 17:18:10-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-18-27 17:18:10-__init__-DEBUG-Using selector: SelectSelector
2019-18-27 17:18:20-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-18-27 17:18:20-__init__-DEBUG-Using selector: SelectSelector
2019-18-27 17:18:28-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-18-27 17:18:28-__init__-DEBUG-Using selector: SelectSelector
2019-18-27 17:18:39-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-18-27 17:18:39-__init__-DEBUG-Using selector: SelectSelector
2019-20-27 17:20:10-log_response-ERROR-Internal Server Error: /apis/create_new_keyspair
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 120, in create_new_keyspair
    pubs["IdentityPub"] = pubs["IdentityPri"].IdentityPri.public_key()
AttributeError: '_X25519PrivateKey' object has no attribute 'IdentityPri'
2019-20-27 17:20:22-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-20-27 17:20:22-__init__-DEBUG-Using selector: SelectSelector
2019-20-27 17:20:25-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-20-27 17:20:25-__init__-DEBUG-Using selector: SelectSelector
2019-20-27 17:20:29-log_response-ERROR-Internal Server Error: /apis/create_new_keyspair
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 129, in create_new_keyspair
    return JsonResponse(result)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\http\response.py", line 587, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _X25519PrivateKey is not JSON serializable
2019-20-27 17:20:39-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-20-27 17:20:39-__init__-DEBUG-Using selector: SelectSelector
2019-21-27 17:21:39-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-21-27 17:21:39-__init__-DEBUG-Using selector: SelectSelector
2019-21-27 17:21:43-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-21-27 17:21:43-__init__-DEBUG-Using selector: SelectSelector
2019-26-27 17:26:28-log_response-ERROR-Internal Server Error: /apis/create_new_keyspair
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 142, in create_new_keyspair
    pubs["IdentityPub"] = binascii.hexlify(pubs["IdentityPri"].public_bytes(
AttributeError: 'bytes' object has no attribute 'public_bytes'
2019-27-27 17:27:25-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-27-27 17:27:25-__init__-DEBUG-Using selector: SelectSelector
2019-27-27 17:27:30-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-27-27 17:27:30-__init__-DEBUG-Using selector: SelectSelector
2019-27-27 17:27:33-log_response-ERROR-Internal Server Error: /apis/create_new_keyspair
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 143, in create_new_keyspair
    pubs["IdentityPub"] = binascii.hexlify(pubs["IdentityPri"].public_bytes(
AttributeError: 'bytes' object has no attribute 'public_bytes'
2019-28-27 17:28:11-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-28-27 17:28:11-__init__-DEBUG-Using selector: SelectSelector
2019-28-27 17:28:16-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-28-27 17:28:16-__init__-DEBUG-Using selector: SelectSelector
2019-28-27 17:28:18-log_response-ERROR-Internal Server Error: /apis/create_new_keyspair
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 155, in create_new_keyspair
    return JsonResponse(result)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\http\response.py", line 587, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
2019-28-27 17:28:47-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-28-27 17:28:47-__init__-DEBUG-Using selector: SelectSelector
2019-28-27 17:28:55-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-28-27 17:28:55-__init__-DEBUG-Using selector: SelectSelector
2019-29-27 17:29:07-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-29-27 17:29:07-__init__-DEBUG-Using selector: SelectSelector
2019-29-27 17:29:13-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-29-27 17:29:13-__init__-DEBUG-Using selector: SelectSelector
2019-29-27 17:29:17-log_response-ERROR-Internal Server Error: /apis/create_new_keyspair
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 155, in create_new_keyspair
    return JsonResponse(result)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\http\response.py", line 587, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
2019-31-27 17:31:57-log_response-ERROR-Internal Server Error: /apis/create_new_keyspair
Traceback (most recent call last):
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Study\School\e2e\app\djangoapp\backend\views.py", line 155, in create_new_keyspair
    return JsonResponse(result)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\http\response.py", line 587, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Pisho\AppData\Roaming\Python\Python37\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "C:\Users\Pisho\AppData\Local\Programs\Python\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
2019-32-27 17:32:13-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-32-27 17:32:13-__init__-DEBUG-Using selector: SelectSelector
2019-32-27 17:32:55-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-32-27 17:32:55-__init__-DEBUG-Using selector: SelectSelector
2019-32-27 17:32:58-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-32-27 17:32:58-__init__-DEBUG-Using selector: SelectSelector
2019-33-27 17:33:26-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-33-27 17:33:26-__init__-DEBUG-Using selector: SelectSelector
2019-33-27 17:33:28-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-33-27 17:33:28-__init__-DEBUG-Using selector: SelectSelector
2019-33-27 17:33:39-trigger_reload-INFO-D:\Study\School\e2e\app\djangoapp\backend\views.py changed, reloading.
2019-33-27 17:33:39-__init__-DEBUG-Using selector: SelectSelector
2019-34-27 17:34:50-__init__-DEBUG-Using selector: SelectSelector
2019-36-27 17:36:11-log_response-WARNING-Not Found: /apis/get_token
